name: ecommerce_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  dio: ^5.3.2
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.0
  intl_phone_field: ^3.2.0
  intl_phone_number_field: ^0.1.7
  intl_phone_number_input: ^0.7.3+1
  shared_preferences: ^2.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Bold.ttf

